collections:
  authors:
    output: true
future: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-mermaid

mermaid:
  src: '/assets/javascript/mermaid.min.js'

theme: jekyll-theme-minimal
#theme: jekyll-theme-hydeout
title: A Fish without a Bicycle
description: Technology and Art
markdown: kramdown
